Add Merkle Tree
LiskHQ/lisk-token-claim pull request #1
Opened 2023-11-30 13:58 UTC by Phanco

### What was the problem?

This PR resolves #2

### How was it solved?
Merkle Tree function implemented, and a script to read balances json

### How was it tested?
Test cases passed at lisk-contract side using the merkle tree and root built by this script

2023-12-04 09:04 UTC, AndreasKendziorra requested changes

2023-12-04 09:04 UTC, AndreasKendziorra commented on README.md
> +$ yarn
I guess you first need to clone and then go into the directory, right?

2023-12-04 09:04 UTC, AndreasKendziorra commented on README.md
> +        address: string;
what is this needed for?

2023-12-04 09:04 UTC, AndreasKendziorra commented on README.md
> +        balanceBeddows: number;
why the two different values?

2023-12-04 09:04 UTC, AndreasKendziorra commented on data/example/balances.json
> +		"balance": 0.55484318
I'm a bit surprised to the see the balance as a fractional number. Wouldn't it be better to store the number of Beddows as an integer?

2023-12-04 09:04 UTC, AndreasKendziorra commented on data/example/create-balances.ts
> +// #51: numSig 2  => 1M + 2O
It took me a to understand that you meant "2 optional keys" instead "twenty" :) Maybe use  lowercase `m` and `o` to avoid the same confusion for other readers.

2023-12-04 09:04 UTC, AndreasKendziorra commented on main.ts
> +	const balanceBeddows = Math.floor(account.balance * LSK_MULTIPLIER);
Similar to my comment above: I'm to 99% sure that works without problems. But why don't we store initially the balance in Beddows as an integer in the json? Then I would be even more sure that it works.

2023-12-04 09:04 UTC, AndreasKendziorra commented on main.ts
> +		? solidityPacked(
what is the payload used for? for computing the leaves in the tree? Because in the specs, I was assuming that we use regular ABI encoding instead of packed encoding. One reason is also that [https://github.com/OpenZeppelin/merkle-tree#standardmerkletreeof](https://github.com/OpenZeppelin/merkle-tree#standardmerkletreeof) uses regular ABI encoding.

2023-12-04 09:04 UTC, AndreasKendziorra commented on main.ts
> +				['bytes20', 'uint64', 'uint256', 'bytes', 'bytes'],
1. the type for `numberOfSignatures` should be `uint32` instead of `uint256`
2. for `mandatoryKeys` and `optionalKeys`, I was specifying the type `bytes32[]` instead of `bytes`. Both ways seem to result into the same encoding (unless that are some malformed keys that are longer or shorter than 32 bytes). I was nevertheless wondering if it's better to use a unique types array in the specs and implementation to avoid any confusion for readers.

2023-12-04 09:04 UTC, AndreasKendziorra commented on main.ts
> +		: solidityPacked(['bytes20', 'uint64', 'uint256'], [address, balanceBeddows, 0]);
1. the type for `numberOfSignatures` should be `uint32` instead of `uint256`
2. I see that this is more space efficient than additionally encoding empty arrays, which still requires some space, as I proposed in the specs. But I would find it a bit cleaner to use the same encoding for every account, i.e., to also encode the empty arrays `mandatoryKeys` and `optionalKeys` here. One reason is also to keep the Merkle tree (or root) construction as simple as possible to reduce the effort to review the tool or to build your own to reduce the required trust into foundation for the claims process.

2023-12-04 09:04 UTC, AndreasKendziorra commented on main.ts
> +const elements = nodes.map(result => toBuffer(result.hash));
1. As far as I can see, a leave of the tree matches with the items specification from lines 23-32. Right? But payload should be sufficient and that's also how I specified it. Or do you think this is not sufficient?
2. I specified that leaves of the tree must be sorted by the `address` property which seems not be the case here.

2023-12-04 09:04 UTC, AndreasKendziorra commented on src/merkle-tree.ts
> +// Ref: https://github.com/Uniswap/merkle-distributor/blob/master/src/merkle-tree.ts
I didn't check this file. But why don't we use the library from OpenZepplin? It's better documented and I also find it even more trustworthy.

2023-12-04 09:04 UTC, AndreasKendziorra commented on main.ts
Shouldn't we have some unit tests for it? For example:

- that the correct encoding is used
- that the leaves are in the correct order

2023-12-04 09:04 UTC, AndreasKendziorra commented on data/example/sign.ts
What's the purpose of this file?

2023-12-04 15:19 UTC, Phanco commented on README.md
> +        address: string;
This is for the ease of cross-checking with the json/csv generated from the snapshot manually.

2023-12-04 15:20 UTC, Phanco commented on README.md
> +        balanceBeddows: number;
Same as above, for manually checking. The tree builder will use beddows instead.

2023-12-04 15:22 UTC, Phanco commented on data/example/balances.json
> +		"balance": 0.55484318
We are not sure about the format or what is given from the snapshot. But I have to put something here as PoC, in this case it showed this script could handle balance in decimal form, which could also handle beddows easily.

2023-12-04 15:24 UTC, Phanco commented on main.ts
> +	const balanceBeddows = Math.floor(account.balance * LSK_MULTIPLIER);
It really depends on the snapshot data, although at this point I would agree that data is also storing in beddows

2023-12-04 15:24 UTC, Phanco commented on data/example/create-balances.ts
> +// #51: numSig 2  => 1M + 2O
:P

2023-12-04 15:26 UTC, Phanco commented on main.ts
> +		: solidityPacked(['bytes20', 'uint64', 'uint256'], [address, balanceBeddows, 0]);
an encoded empty array is an empty string, so it makes no difference here

2023-12-04 15:29 UTC, Phanco commented on data/example/sign.ts
It signs all claims and store as `signatures.json`. Of course it is for testing/demonstration purpose

2023-12-04 15:30 UTC, Phanco commented on src/merkle-tree.ts
> +// Ref: https://github.com/Uniswap/merkle-distributor/blob/master/src/merkle-tree.ts
I didn't know OZ also made a JS library for this, will switch to that one

2023-12-04 15:38 UTC, Phanco commented on main.ts
> +				['bytes20', 'uint64', 'uint256', 'bytes', 'bytes'],
I was using abiEncodePacked from the contract, which does not accept arrays, that's why I am using `bytes` here, which concats every elements from the keys array.

I will check out the abiEncode method from ethers.

2023-12-04 15:40 UTC, Phanco commented on main.ts
> +const elements = nodes.map(result => toBuffer(result.hash));
node is the hash while payload here I define it as the encoded Data (before hash)

2023-12-05 12:56 UTC, matjazv commented on main.ts
> +	const balanceBeddows = Math.floor(account.balance * LSK_MULTIPLIER);
When we'll know format of snapshot data to be able to decide what type of variables/parameters we would need to use?

2023-12-05 12:59 UTC, matjazv commented on data/example/sign.ts
Could this file be refactored in a way that we could use it as a library for generating signatures? And then create another example file to use this library?
I think it would be beneficial to have something like this.

Or do we have a plan to create another issue which will deal with it?

2023-12-05 15:07 UTC, shuse2 reviewed
Since in this repo, there will be multiple functionality
* Library
* CLI
* Server?

it would be nice to prepare it as monorepo?

2023-12-05 15:11 UTC, shuse2 commented on main.ts
> +	const balanceBeddows = Math.floor(account.balance * LSK_MULTIPLIER);
I assume the `snapshot` will be just database data from `lisk-db`. so we will need to decode and format it where it's needed

2023-12-07 15:34 UTC, Phanco commented on main.ts
> +	const balanceBeddows = Math.floor(account.balance * LSK_MULTIPLIER);
To remove the ambiguity, now I assume the snapshot has balance in beddows, and removed this multiplication step out of the tree building process

2023-12-07 15:54 UTC, Phanco commented on data/example/balances.json
> +		"balance": 0.55484318
Now balances.json also has `Beddows`

2023-12-07 15:54 UTC, Phanco commented on main.ts
> +		? solidityPacked(
updated to be using OZ lib

2023-12-07 15:54 UTC, Phanco commented on main.ts
> +				['bytes20', 'uint64', 'uint256', 'bytes', 'bytes'],
updated to be using OZ lib

2023-12-07 15:55 UTC, Phanco commented on main.ts
> +		: solidityPacked(['bytes20', 'uint64', 'uint256'], [address, balanceBeddows, 0]);
Updated, both accounts use the same encoding method

2023-12-07 15:56 UTC, Phanco commented on data/example/sign.ts
Good question, we can work closely with UI team to see how the sign module should be implemented

2023-12-08 14:00 UTC, Phanco commented on main.ts
Added

2023-12-08 14:43 UTC, matjazv requested changes

2023-12-08 14:43 UTC, matjazv commented on README.md
> +This library builds Merkle Tree and build Merkle Root
```suggestion
This library builds Merkle Tree from a snapshot and computes Merkle Root.
```

2023-12-08 14:43 UTC, matjazv commented on README.md
> +    balance: number;
`balanceBeddows` is missing?

2023-12-08 14:43 UTC, matjazv commented on README.md
> +`merkle-tree-simple.json` is a lightweight version of `merkle-tree.json`, which also has sufficient params for claiming.
Are files `merkle-tree-simple.json` and `merkle-tree.json` generated by some script/external SW or are they missing in this commit?

2023-12-08 14:43 UTC, matjazv commented on README.md
> +    nodes: {
`leaves` probably?

2023-12-08 14:43 UTC, matjazv commented on README.md
> +        payload: string;
Is `payload` used somewhere?
In `merkle-tree-result.json` file I can't find it.

2023-12-08 14:43 UTC, matjazv commented on data/example/merkle-tree-result-simple.json
Inside this file there is a field `b32Address`.
This field is not mentioned in README.md.

2023-12-08 14:43 UTC, matjazv commented on README.md
> +
Why is structure of `signatures.json` not listed here?

2023-12-08 15:17 UTC, Phanco commented
So sorry the README was not updated accordingly, now it has been updated

2023-12-08 15:18 UTC, Phanco commented on README.md
> +    balance: number;
Updated

2023-12-08 15:18 UTC, Phanco commented on README.md
> +This library builds Merkle Tree and build Merkle Root
Updated

2023-12-08 15:18 UTC, Phanco commented on README.md
> +`merkle-tree-simple.json` is a lightweight version of `merkle-tree.json`, which also has sufficient params for claiming.
Updated

2023-12-08 15:18 UTC, Phanco commented on README.md
> +    nodes: {
Updated

2023-12-08 15:18 UTC, Phanco commented on data/example/merkle-tree-result-simple.json
Updated

2023-12-08 15:18 UTC, Phanco commented on README.md
> +
Updated

2023-12-08 15:19 UTC, Phanco commented on README.md
> +        payload: string;
payload is a field to manually compare with existing data, however OZ's lib does not have a function to generate abi-encoded message so now I have removed it

2023-12-08 16:03 UTC, matjazv requested changes

2023-12-08 16:03 UTC, matjazv commented on src/interface.ts
> +		payload: string;
Probably here could `payload` also be removed?

2023-12-08 16:03 UTC, matjazv commented on README.md
> +`merkle-tree-simple.json` is a lightweight version of `merkle-tree-result.json`, which also has sufficient params for claiming.
`merkle-tree-simple.json` -> `merkle-tree-result-simple.json`?

2023-12-12 10:15 UTC, AndreasKendziorra commented on README.md
> +$ yarn
I was actually serious that this should be added to the README :) but ignore it if you don't agree

2023-12-13 11:13 UTC, AndreasKendziorra requested changes

2023-12-13 11:13 UTC, AndreasKendziorra commented on README.md
> +| `/data/<network>/balance.json`                   | Stores balance by address after a snapshot is taken, addresses must be sorted in ascending order. | Snapshot                      |
it also stores information about keys

2023-12-13 11:13 UTC, AndreasKendziorra commented on README.md
> +### `merkle-tree-simple`
Is there really a need to create two merkle tree json files? wouldn't the regular one be sufficient?

2023-12-13 11:13 UTC, AndreasKendziorra commented on README.md
> +### `merkle-tree-simple`
If the Foundry limitation with regard to decimal numbers is the reason to the create the "simple" version of the json file, I would rather remove the decimals number from the json, i.e. use only integers to express balances in beddows.

2023-12-13 11:13 UTC, AndreasKendziorra commented on data/example/create-balances.ts
>  	const balance = randomBalance(index);
I know it doesn't really matter as it's just for testing. But since the sorting is now done w.r.t. address, the balances don't need to be sorted and it would actually be a bit nicer if they aren't. So, you could just assign any random float number and then the function `randomBalance` could also be removed.

2023-12-13 11:13 UTC, AndreasKendziorra commented on data/example/sign.ts
>  		// Signing all keys regardless of required amount
you mean "regardless of the required number of signatures" right?

2023-12-13 11:13 UTC, AndreasKendziorra commented on main.ts
> +	balances = JSON.parse(fs.readFileSync(`${path}/balances.json`, 'utf-8')) as Balance[];
at this point, I think it may be helpful to rename `balances.json` to `accounts.json` and `balances` to `accounts` such that it is more obvious whats happening here. Namely, that the accounts including balances and keys are parsed.

2023-12-13 11:13 UTC, AndreasKendziorra commented on src/interface.ts
> +export interface Balance {
Maybe `Account` instead of `Balance`?

2023-12-13 11:13 UTC, AndreasKendziorra commented on src/interface.ts
> +export interface Balances {
`Accounts` instead of `Balances`?

2023-12-13 11:13 UTC, AndreasKendziorra commented on test/main.spec.ts
> +	) as MerkleTree;
I think this approach is not reliable as it is not assured that this json file is updated whenever `main.ts` is updated. Do you agree?
Maybe `main.ts` could have an additional optional argument for the file name of the output file. Then, one could create such a json during the test setup. If it's too time consuming, one could maybe also reduce the number of accounts for the tests. Maybe just 5 instead of 50 accounts.

2023-12-13 11:13 UTC, AndreasKendziorra commented on test/main.spec.ts
> +					leaf.optionalKeys,
1. this does not really ensure that these values are correctly derived from the input. So, if you think the effort is acceptable, it may be the best to:
    - create a json document with the input data (structure matches with `balances.json`) in this test file. It contains only 2 or 3 accounts. They must actually be sorted by address, because main.ts is assuming this.
    - run main.ts with this input during the test setup. It requires to change main.ts to allow to specify the input file.
    - replace the `leaf.<property>` entries in line 16-20 by the values contained in the input json.

2. Moreover, an additional test should be created where the accounts in the input file are not sorted. The expectation is that main.ts throws.

2023-12-13 11:13 UTC, AndreasKendziorra commented on test/main.spec.ts
> +	});
this test ensures that entries in the output file are sorted correctly, but it does not ensure that the tree used for computing `root` was correctly sorted. Or even more generally, it was not tested that `root` was computed correctly (correct input values in correct order). Is it easy to mock `StandardMerkleTree.of` and add a test where the expectation is that this is called with certain input values?

2024-01-02 13:10 UTC, Phanco commented on README.md
> +### `merkle-tree-simple`
The philosophy of having 2 files is to make `merkle-tree-result` as detailed as possible, even if some fields are very trivial. As that file would be published to and reviewed by third party, by do that those params could be even be verified by naked eye.

2024-01-03 10:15 UTC, Phanco commented on README.md
> +$ yarn
Added :D

2024-01-04 08:46 UTC, AndreasKendziorra commented on README.md
> +| `/data/<network>/accounts.json`                  | Stores addresses, balances, and multisig details(If any) by address after a snapshot is taken, addresses must be sorted in ascending order. | Snap
```suggestion
| `/data/<network>/accounts.json`                  | Stores addresses, balances, and multisig details (If any) per account after a snapshot is taken, addresses must be sorted in ascending order. | Snapshot                                |
```

2024-01-04 08:46 UTC, AndreasKendziorra commented on data/example/sign.ts
>  		// Signing all keys regardless of required amount
This was meant as a suggestion to change it to "regardless of the required number of signatures" ;)

2024-01-04 09:08 UTC, AndreasKendziorra commented on README.md
> +### `merkle-tree-simple`
1. Is my understanding correct that `merkle-tree-result-simple.json` will be used by the UI (or its backend service) to create inclusion proofs, and `merkle-tree-result.json` is only intended to be read by humans? If so, I would say that the first one is THE merkle tree file and I would not add the term "simple" to its name. So maybe
`merkle-tree-result-simple.json` --> `merkle-tree-result.json`
`merkle-tree-result.json` --> `merkle-tree-result-detailed.json`
2. It would be good to extend the description in the [Files](https://github.com/LiskHQ/lisk-token-claim/blob/a9037d697a9043f271f82066f41520faca73ee6c/README.md#files) section such that it's clear for everyone what's the purpose of the individual files.

2024-01-04 10:52 UTC, AndreasKendziorra requested changes

2024-01-04 10:52 UTC, AndreasKendziorra commented on README.md
> +| `/data/<network>/accounts.json`                  | Stores addresses, balances, and multisig details(If any) by address after a snapshot is taken, addresses must be sorted in ascending order. | Snap
An additional hint that this is used as the input for Merkle tree computation would be helpful. Once we know how the snapshot and this file are computed, it would additionally be good to mention this here as well.

2024-01-04 10:52 UTC, AndreasKendziorra commented on README.md
>  This library builds Merkle Tree from a snapshot and computes Merkle Root.
As the deployment script for the claims process uses now a json file that contains only the Merkle root, it would probably be helpful to additionally generate this file with the scripts here as well. Do you agree?
If so, I would call it (and rename the one in the deployment script to) `merkle-root.json` or similar instead of `merkle-tree.json`.

2024-01-04 10:52 UTC, AndreasKendziorra commented on src/buildTree.ts
> +	for (const [index, balance] of accounts.entries()) {
`account` instead of `balance`?

2024-01-04 10:52 UTC, AndreasKendziorra commented on src/buildTree.ts
> +			const address = cryptography.address.getAddressFromLisk32Address(account.lskAddress);
I think this line is not needed, right?

2024-01-04 10:52 UTC, AndreasKendziorra commented on test/buildTree.spec.ts
> +			expect(merkleTree.tree.getProof(createPayload(accountOfLeaf))).toEqual(leaf.proof);
we could additionally check that the proof is valid against the root stored in `merkleTree.tree.root` using [`.verify`](https://github.com/OpenZeppelin/merkle-tree#treeverify).

2024-01-04 10:52 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +    }
a check for the property `address` is missing.

2024-01-04 16:04 UTC, Phanco commented on README.md
> +### `merkle-tree-simple`
`merkle-tree-result.json` will be read by 3rd party, and the public, they would do it however that like.

But I agree renaming it to `detailed`

2024-01-04 16:05 UTC, Phanco commented on README.md
>  This library builds Merkle Tree from a snapshot and computes Merkle Root.
Can do

2024-01-04 16:59 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +    }
Updated

2024-01-04 16:59 UTC, Phanco commented on test/buildTree.spec.ts
> +			expect(merkleTree.tree.getProof(createPayload(accountOfLeaf))).toEqual(leaf.proof);
Updated

2024-01-04 16:59 UTC, Phanco commented on src/buildTree.ts
> +			const address = cryptography.address.getAddressFromLisk32Address(account.lskAddress);
Updated

2024-01-04 16:59 UTC, Phanco commented on src/buildTree.ts
> +	for (const [index, balance] of accounts.entries()) {
Updated

2024-01-04 17:06 UTC, Phanco commented on README.md
> +| `/data/<network>/accounts.json`                  | Stores addresses, balances, and multisig details(If any) by address after a snapshot is taken, addresses must be sorted in ascending order. | Snap
Updated

2024-01-04 17:06 UTC, Phanco commented on README.md
> +| `/data/<network>/accounts.json`                  | Stores addresses, balances, and multisig details(If any) by address after a snapshot is taken, addresses must be sorted in ascending order. | Snap
Updated

2024-01-05 09:24 UTC, AndreasKendziorra requested changes

2024-01-05 09:24 UTC, AndreasKendziorra commented on README.md
> +| `/data/<network>/merkle-tree-result.json`          | Stores MerkleRoot, and leaves for each account. Will be used for testing and simulation for Claim Contract.
I'm not 100%ly sure what you mean with "simulation for Claim Contract". Will it be used by the UI to get the inclusion proof?

2024-01-05 09:24 UTC, AndreasKendziorra commented on data/example/sign.ts
> +		// Signing all keys regardless of required amount of numberOfSignatures
```suggestion
		// Signing with all keys regardless of the required number of signatures
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTree.spec.ts
> +			// Verify Proof is part of MerkleRoot
```suggestion
			// Verify Proof is valid with respect to MerkleRoot
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTree.spec.ts
>  		for (const leaf of merkleTree.leaves) {
Somehow this comment got lost in my last review:

Using [`.entries`](https://github.com/OpenZeppelin/merkle-tree#treeentries), we could additionally check that the leaves of the tree are indeed in the correct order:
```js
for (const [i, leaf] of merkleTree.tree.entries()) {
  expect(leaf.lskAddress).toEqual(accounts[i].lskAddress);
}
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on README.md
the heading in line 86 must also be updated

2024-01-05 09:24 UTC, AndreasKendziorra commented on README.md
>  Due to the constraint of vm.parseJson in Foundry, fields in `merkle-tree-result` such as decimal field will trigger error.
```suggestion
Due to the constraint of vm.parseJson in Foundry, fields in `merkle-tree-result-detailed` such as decimal field will trigger error.
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on README.md
> +`merkle-tree-simple.json` is a lightweight version of `merkle-tree-result-detailed.json`, which also has sufficient params for claiming.
```suggestion
`merkle-tree-result.json` is a lightweight version of `merkle-tree-result-detailed.json`, which also has sufficient params for claiming.
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-${timestamp}.json`,
```suggestion
				`${path}/merkle-tree-result-detailed-${timestamp}.json`,
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-simple-${timestamp}.json`,
```suggestion
				`${path}/merkle-tree-result-${timestamp}.json`,
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +			// Backing-up existing, ensure both files are newly built during testing
we should also backup `merkle-root.json`, right?

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-${timestamp}.json`,
```suggestion
				`${path}/merkle-tree-result-detailed-${timestamp}.json`,
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-simple-${timestamp}.json`,
```suggestion
				`${path}/merkle-tree-result-${timestamp}.json`,
```

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +		const merkleTreeResultJSON = JSON.parse(
I would rename this one to `merkleTreeResultDetailedJSON` and `merkleTreeResultSimpleJSON` to `merkleTreeResultJSON`

2024-01-05 09:24 UTC, AndreasKendziorra commented on test/buildTreeJSON.spec.ts
> +	it('should build JSON files with correct params', () => {
I would also test `merkle-root.json`

2024-01-08 15:59 UTC, Phanco commented on README.md
>  Due to the constraint of vm.parseJson in Foundry, fields in `merkle-tree-result` such as decimal field will trigger error.
This paragraph is removed

2024-01-08 15:59 UTC, Phanco commented on README.md
> +`merkle-tree-simple.json` is a lightweight version of `merkle-tree-result-detailed.json`, which also has sufficient params for claiming.
This paragraph is removed

2024-01-08 15:59 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-${timestamp}.json`,
The backup part is removed since example data will not be committed

2024-01-08 15:59 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-simple-${timestamp}.json`,
The backup part is removed since example data will not be committed

2024-01-08 15:59 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +			// Backing-up existing, ensure both files are newly built during testing
The backup part is removed since example data will not be committed

2024-01-08 15:59 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-${timestamp}.json`,
The backup part is removed since example data will not be committed

2024-01-08 16:00 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +				`${path}/merkle-tree-result-simple-${timestamp}.json`,
The backup part is removed since example data will not be committed

2024-01-09 10:35 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +	it('should build JSON files with correct params', () => {
Updated

2024-01-09 10:35 UTC, Phanco commented on test/buildTreeJSON.spec.ts
> +		const merkleTreeResultJSON = JSON.parse(
Updated

2024-01-09 10:35 UTC, Phanco commented
All comments have been tackled, and the proj is moved into package folder 🙇

2024-01-10 12:46 UTC, shuse2 requested changes

2024-01-10 12:46 UTC, shuse2 commented on tsconfig.json
> +		"noImplicitAny": false,
why no implicit any? 😢

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +import * as fs from 'fs';
let's keep the file name in snake case (both for src and test)

2024-01-10 12:46 UTC, shuse2 commented on README.md
> +$ git clone git@github.com:LiskHQ/lisk-token-claim.git && cd lisk-token-claim
probably clone part is not so important in readme. everyone should know how to clone

2024-01-10 12:46 UTC, shuse2 commented on jest.config.js
> +};
seams like jest is not used?

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/package.json
> +		"lisk-sdk": "^6.0.0",
instead of installing full sdk, probably good to just add `@liskhq/lisk-client` or specific libraries

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/example/create-accounts.ts
> +import { cryptography } from 'lisk-sdk';
this example folder should be out side of `src`?

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +	console.log('===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====');
if you want to add logs for debug, it would probably be better to use `debug` library

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +import * as fs from 'fs';
Also, `applications` maybe doesn't fit with the contents

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTree.ts
> +			address: '0x' + address.toString('hex'),
maybe it's better to create a util function to covert buffer to hex with leading 0x since it's used multiple times

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +	const merkleRootJSONPath = `${path}/merkle-root.json`;
path generation should be handled with `path` library

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		const path = `../../data/${network}`;
path should be built with `path` library. Also, once this is built for actual use, this path won't make sense

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		}),
how would this network flag be used? the source data will be database, so there at least it will not relate to the network

2024-01-10 12:46 UTC, shuse2 commented on packages/tree-builder/src/applications/example/sign-accounts.ts
> +		fs.readFileSync('../../data/example/keyPairs.json', 'utf-8'),
is this more like a test file?

2024-01-10 12:52 UTC, Phanco commented on README.md
> +$ git clone git@github.com:LiskHQ/lisk-token-claim.git && cd lisk-token-claim
@AndreasKendziorra sorry I'm removing it😿

2024-01-10 12:54 UTC, Phanco commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		}),
the source data would be a JSON file, and the JSON file will be built from `snapshot-taker`. Tree builder would not interact directly with db or blockchain

2024-01-10 12:56 UTC, Phanco commented on tsconfig.json
> +		"noImplicitAny": false,
with impllicitAny be true I will get errors from lisk-sdk and build fail 😢 
```
../../node_modules/@liskhq/lisk-p2p/dist-node/types.d.ts:2:32 - error TS7016: Could not find a declaration file for module 'socketcluster-server'. '/Users/francong/Desktop/lisk/lisk-token-claim/node_modules/socketcluster-server/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/socketcluster-server` if it exists or add a new declaration (.d.ts) file containing `declare module 'socketcluster-server';`

2 import { SCServerSocket } from 'socketcluster-server';
                                 ~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@liskhq/lisk-utils/dist-node/objects/index.d.ts:1:28 - error TS7016: Could not find a declaration file for module 'lodash.clonedeep'. '/Users/francong/Desktop/lisk/lisk-token-claim/node_modules/lodash.clonedeep/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash.clonedeep` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.clonedeep';`

1 import cloneDeep = require('lodash.clonedeep');
                             ~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

2024-01-10 13:02 UTC, Phanco commented on tsconfig.json
> +		"noImplicitAny": false,
oh seems that I can use `noImplicitAny` again if I change importing `lisk-sdk` to `@liskhq/lisk-cryptography`. Updating

2024-01-10 13:02 UTC, Phanco commented on packages/tree-builder/package.json
> +		"lisk-sdk": "^6.0.0",
Updating to use `@liskhq/lisk-cryptography` instead

2024-01-10 13:23 UTC, Phanco commented on packages/tree-builder/src/applications/example/create-accounts.ts
> +import { cryptography } from 'lisk-sdk';
`example` is also a command, so I think it should be kept in `applications` like other commands

2024-01-10 14:07 UTC, Phanco commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +	console.log('===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====');
The log is a proper output, not only for debug

2024-01-10 17:13 UTC, Phanco commented on packages/tree-builder/src/applications/example/sign-accounts.ts
> +		fs.readFileSync('../../data/example/keyPairs.json', 'utf-8'),
also for demo and to prepare data for future benchmark purpose

2024-01-11 08:59 UTC, AndreasKendziorra requested changes

2024-01-11 08:59 UTC, AndreasKendziorra commented on packages/tree-builder/README.md
> +$ ./bin/run.js generate-merkle-tree --network=mainnet # Testnet
`--network=testnet`?

2024-01-11 08:59 UTC, AndreasKendziorra commented on packages/tree-builder/test/applications/build_tree.ts
> +			const accountOfLeaf = accounts.find(account => account.lskAddress === leaf.lskAddress)!;
optional: this is not really needed anymore, because you could just use `accounts[i]` instead of `accountOfLeaf`.

2024-01-11 08:59 UTC, AndreasKendziorra commented on packages/tree-builder/src/applications/example/sign_accounts.ts
> +			// Signing with all keys regardless of the required amount of number of signatures
```suggestion
			// Signing with all keys regardless of the required number of signatures
```

2024-01-11 14:30 UTC, Phanco commented on packages/tree-builder/README.md
> +$ ./bin/run.js generate-merkle-tree --network=mainnet # Testnet
Updated

2024-01-11 14:30 UTC, Phanco commented on packages/tree-builder/test/applications/build_tree.ts
> +			const accountOfLeaf = accounts.find(account => account.lskAddress === leaf.lskAddress)!;
Updated

2024-01-11 14:30 UTC, Phanco commented on packages/tree-builder/src/applications/example/sign_accounts.ts
> +			// Signing with all keys regardless of the required amount of number of signatures
Updated

2024-01-12 10:12 UTC, shuse2 commented on tsconfig.json
> +		"noImplicitAny": false,
In that case, `skipLibCheck` should be used instead of `noImplicitAny`, but let's change to lisk-cryptography

2024-01-12 10:30 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +	console.log('===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====');
then i think it should use logger given in the command

2024-01-12 10:34 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		}),
didn't we discuss to have only 2 packages?
im not sure how this intermediate JSON file would help since it won't be used anywhere else.

Also, how would the network change the output?

2024-01-12 10:40 UTC, shuse2 commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +	const merkleRootJSONPath = `${path}/merkle-root.json`;
here i meant `/` shoulnd't be used since it change based on the environment. so in above case, it would be more like `path.join(path, merkle-root.json)`

2024-01-12 10:47 UTC, Phanco commented on packages/tree-builder/src/applications/buildTreeJSON.ts
> +	const merkleRootJSONPath = `${path}/merkle-root.json`;
Yes it has been updated this way, thank you :D

2024-01-17 11:21 UTC, Phanco commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		}),
Solely at the scope of this PR, the builder will read a JSON and the user could choose input/output folder by specifying network. In the next PR this approach will be changed and user will be asked for the path of db instead.

2024-01-17 13:19 UTC, Phanco commented
UPDATE: This PR focuses on Merkle Tree building, the method of account reading will be changed in the another PR.

2024-01-17 13:31 UTC, AndreasKendziorra approved these changes

2024-01-18 07:25 UTC, matjazv approved these changes

2024-01-19 08:27 UTC, shuse2 commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +export function build_tree(accounts: Account[]): {
```suggestion
export function buildTree(accounts: Account[]): {
```

2024-01-19 08:31 UTC, shuse2 commented on packages/tree-builder/package.json
> +		"sinon": "^17.0.1",
`sinon` should be devDependencies

2024-01-19 08:33 UTC, shuse2 commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +import { debug, log } from 'oclif/lib/log';
is this really globally accessible?
in the command context, it's using `this.log`, so it looks bit strange to directly use this

2024-01-19 11:28 UTC, Phanco commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +import { debug, log } from 'oclif/lib/log';
I tried passing `this.log` into functions but it returned error because of misalignment of `this` scope. According to this closed [issue](https://github.com/oclif/oclif/issues/881) from oclif, this.log could not be used outside commands.

The best workaround I could do is to use the `ux` from `@oclif/core`. But the `debug` does not work (even using `debug` from npm). So I removed them, and users may verify outputs by the output instead of the log.

2024-01-19 11:28 UTC, Phanco commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +export function build_tree(accounts: Account[]): {
updated 👍

2024-01-19 14:31 UTC, shuse2 approved these changes

2024-01-19 14:31 UTC, merged