Comprehensive documentation
LiskHQ/lisk-token-claim pull request #11
Opened 2024-02-09 11:37 UTC by Phanco

### What was the problem?

This PR resolves #10

### How was it solved?
1. Updated README on both repos
2. Added `/documentation` folder

2024-02-14 15:56 UTC, matjazv requested changes

2024-02-14 15:56 UTC, matjazv commented on packages/claim-backend/README.md
>  This library supplies leaf details to frontend. It also stores partial signatures of claims from multisig addresses.
`This library supplies leaf details to frontend.`

Maybe we could extend this a little bit more and explain some more details?

2024-02-14 15:56 UTC, matjazv commented on packages/claim-backend/README.md
> +1. Docker (Latest Version Recommended) **or**
Is `or` correct or should it be `and`?

2024-02-14 15:56 UTC, matjazv commented on documentation/README.md
> +- Should read all account balances from Lisk Blockchain directly.
```suggestion
- Should read all account balances from Lisk Network directly.
```

2024-02-14 16:29 UTC, Phanco commented on packages/claim-backend/README.md
> +1. Docker (Latest Version Recommended) **or**
or, if a proper PostgreSQL is installed locally, then Docker is not needed

2024-02-20 08:17 UTC, matjazv requested changes

2024-02-20 08:17 UTC, matjazv commented on packages/claim-backend/README.md
> +## Endpoints
Two endpoints are listed below.
Are those two the only present endpoints?
If not, maybe all endpoints should be listed?

2024-02-20 14:37 UTC, AndreasKendziorra requested changes

2024-02-20 14:37 UTC, AndreasKendziorra commented on README.md
> +This repository is a monorepo for essential non-contract services for Token Claim.
```suggestion
This repository is a monorepo for essential non-contract services for the LSK Token Claim on the Lisk L2.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on README.md
> +In this monorepo there are currently 2 repositories:
Is it really common terminology talk about "repositorires" inside a monorepo? If not, then the heading "Repositories" must also be changed.

2024-02-20 14:37 UTC, AndreasKendziorra commented on README.md
>  Builds Merkle Tree from a snapshot and computes Merkle Root.
```suggestion
Builds a Merkle Tree from a snapshot and computes the Merkle Root.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on README.md
>  The database is using PostgreSQL
```suggestion
The database is using PostgreSQL.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +This document states the general requirement of each library in this monorepo.
```suggestion
This document states the general requirements of each library in this monorepo.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +This document states the general requirement of each library in this monorepo.
I would not say "This document states ..." when it's actually just this section that states the requirements

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +## Requirements
From the heading "Requirements" I would actually expect the requirements that need to be fulfilled such that each product works. But instead, the features of the products are listed. Therefore, maybe "Features"?

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +### Requirement for Tree Builder
If we keep the term "requirement", then it must be plural. The same for Claim Backend.

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +- Should build Merkle Tree and Proof according to accounts gathered from Blockchain.
```suggestion
- Should build Merkle tree and proofs according to the accounts gathered from the blockchain.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +- Should build Merkle Tree and Proof according to accounts gathered from Blockchain.
> accounts gathered from Blockchain

This suggests that it reads from a node, but instead it uses a snapshot file, right?

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +- Should response corresponding Merkle Leaf correctly upon request.
```suggestion
- Should return corresponding Merkle Leaf upon request.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
> +## Requirements
Nevertheless, it would be good to list such requirements somewhere, either here or in the documentation of the packages. For instance, one requirement for the tree builder is to have snapshot file...if I remember correctly.

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/README.md
I'm a bit unsure what the purpose of this file is. The diagram makes sense to give an overview how the two packages interact with each other.
But then this little section "Requirements" looks a bit lost. I think one should have a comprehensive documentation for each package and either link to them from here, or have or move these documentation to here. And the "Requirements" section from should be removed from here (and potentially incorporated into the comprehensive documentations of the packages).

2024-02-20 14:37 UTC, AndreasKendziorra commented on documentation/Tech Design - Claims Process.pdf
If this file is supposed to stay here, then it should be linked from `documentation/README.md` with some introduction. For the introduction, it depends on the purpose of the file, which is not totally clear to me yet (I didn't read everything yet). Is it a more detail version of the documentation? Or is it complementing the documentation here, i.e., the parts of the documentation are in the pdf and the remaining part here and both parts do not overlap?

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +This library supplies leaf details to frontend by providing an endpoint that responds with details necessary for the claim. It also stores partial signatures of claims from multisig addresses.
>This library supplies leaf details

I guess for most readers it is not clear what is contained in a leaf. And maybe not even what kind of leaf is meant here.

Suggestion: 
"This library provides information to the frontend by providing an endpoint that responds with details necessary for a token claim..."

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +It accepts POST request with param lskAddress. If the address has eligible LSK to claim, it will return amount of token (account), proof and, should this address owns any multisig account, it will al
```suggestion
It accepts POST request with param `lskAddress`. If the address is eligible for claiming some LSK, it will return the amount of tokens (account), proof and, should this address match to any public of a multisignature account, it will also be displayed here (multisigAccounts).
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +It accepts POST request with param lskAddress. If the address has eligible LSK to claim, it will return amount of token (account), proof and, should this address owns any multisig account, it will al
The parameters in brackets, i.e. "account" and "multisigAccounts" might be confusing when the reader does not know the format of the response. So, I would either remove it or specify also the output format.

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +After the user has signed a multisig signature, this API will be called to record the signature to backend DB.
```suggestion
After the user has signed a claim message for a multisignature account, this API will be called to store the signature at the backend DB.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +If this endpoint is submitted by the last signer of the multisig account, the 200 response will show "ready": true.
```suggestion
If this endpoint is submitted by the last signer of the multisig account, the 200 response will show `"ready": true`.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +In that case the UI could call `/checkEligibility` again to obtain all signatures and submit to smart contract.
```suggestion
In that case the UI could call `/checkEligibility` again to obtain all signatures and submit the claim transaction.
```

2024-02-20 14:37 UTC, AndreasKendziorra commented on packages/tree-builder/README.md
> +This library is a command-line service that builds Merkle Tree from a snapshot and computes Merkle Root.
```suggestion
This library is a command-line service that builds a Merkle tree from a snapshot and computes the Merkle root.
```

2024-02-21 09:43 UTC, Phanco commented on packages/claim-backend/README.md
> +## Endpoints
There are only 2 endpoints in this backend 😆

2024-02-21 10:22 UTC, Phanco commented on README.md
> +In this monorepo there are currently 2 repositories:
Did some googling seems people uses `packages` more, updating ...

2024-02-21 10:43 UTC, Phanco commented on documentation/README.md
> +## Requirements
Since we now have tech design in the repo, I do agree that we can rename it as `Features` to represent a higher-level specification

2024-02-21 12:44 UTC, Phanco commented on documentation/README.md
I also see there's some overlap between `documentation/README.md` and other docs esp. Tech Design. I have removed that README and added more description about the Tech Design PDF on other pages

2024-02-23 13:01 UTC, AndreasKendziorra requested changes

2024-02-23 13:01 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +This package supplies Leaf details to frontend by providing an endpoint that responds with details necessary for the claim. It also stores partial signatures of claims from multisig addresses. Detail
```suggestion
This package supplies Leaf details to frontend by providing an endpoint that responds with details necessary for the claim. It also stores partial signatures of claims from multisig addresses. Details of Leaf can be obtained from [Tech Design](../../documentation/Tech_Design_Claims_Process.pdf).
```

2024-02-23 13:01 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +It accepts POST request with param lskAddress. If the address has eligible LSK to claim, it will return amount of token (account), proof and, should this address owns any multisig account, it will al
> The parameters in brackets, i.e. "account" and "multisigAccounts" might be confusing when the reader does not know the format of the response. So, I would either remove it or specify also the output format.

Did you overlook this part, or did you decide to keep it as it is?

2024-02-26 11:19 UTC, Phanco commented on packages/claim-backend/README.md
> +It accepts POST request with param lskAddress. If the address has eligible LSK to claim, it will return amount of token (account), proof and, should this address owns any multisig account, it will al
I did overlook sorry, added sample response to better describe what's (account) and (multisigAccounts)

2024-02-26 11:19 UTC, Phanco commented on packages/claim-backend/README.md
> +This package supplies Leaf details to frontend by providing an endpoint that responds with details necessary for the claim. It also stores partial signatures of claims from multisig addresses. Detail
updated 👍

2024-02-26 11:43 UTC, AndreasKendziorra requested changes

2024-02-26 11:43 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +(signatures) field stores valid signatures of addresses in multiAccounts, which are previously submitted by `/submitMultisig`.
```suggestion
`signatures` field stores valid signatures of addresses in multiAccounts, which are previously submitted by `/submitMultisig`.
```

2024-02-26 11:43 UTC, AndreasKendziorra commented on packages/claim-backend/README.md
> +It accepts POST request with param `lskAddress`. If the address is eligible for claiming some LSK, it will return the amount of tokens (account), proof and, should this address match to any public ke
```suggestion
It accepts POST request with param `lskAddress`. If the address is eligible for claiming some LSK, it will return the amount of tokens (under `account`), proof and, should this address match to any public key of a multisignature account, it will also be displayed here (under `multisigAccounts`).
```

2024-02-26 12:00 UTC, matjazv approved these changes

2024-02-26 12:29 UTC, AndreasKendziorra approved these changes

2024-02-26 14:20 UTC, merged