Add deployment script
LiskHQ/lisk-token-claim pull request #13
Opened 2024-02-12 16:45 UTC by shuse2

### What was the problem?

This PR resolves #12 

### How was it solved?

* Add docker scripts
* Add deployment scripts

### How was it tested?

* build and run docker locally
* Run staging and production deployment scripts

2024-02-20 08:08 UTC, matjazv requested changes
Why is this comment present?
`This branch had an error being deployed`

2024-02-20 08:08 UTC, matjazv commented on scripts/generate_merkle_tree.sh
> +aws s3 cp $OUTPUT_DIR s3://$S3_BUCKET_NAME/$FOLDER_NAME --recursive
Where is `S3_BUCKET_NAME` set?
Is this a private variable which behaves like a secret?

2024-02-20 10:14 UTC, Phanco commented on .dockerignore
> +**/.mocharc.jsono
.mocharc.json?

2024-02-20 20:32 UTC, shuse2 commented on scripts/generate_merkle_tree.sh
> +aws s3 cp $OUTPUT_DIR s3://$S3_BUCKET_NAME/$FOLDER_NAME --recursive
S3_BUCKET_NAME is set as environment variable locally to keep it generic to put anywhere

2024-02-20 20:56 UTC, shuse2 commented
@matjazv it failed during test because the full setup was not ready

2024-02-22 08:03 UTC, matjazv requested changes

2024-02-22 08:03 UTC, matjazv commented on scripts/generate_merkle_tree.sh
> +if [ ! -d "./tmp/blockchain.db" ]; then
Should be here `-f`?

2024-02-22 08:41 UTC, shuse2 commented on scripts/generate_merkle_tree.sh
> +if [ ! -d "./tmp/blockchain.db" ]; then
blockchain.db is actually directory in the snapshot, and it contains blockchain.db and state.db 😢

2024-02-22 08:44 UTC, matjazv approved these changes

2024-02-22 09:52 UTC, Phanco approved these changes

2024-02-22 15:12 UTC, merged