Add Generate Merkle Tree command and test cases
LiskHQ/lisk-token-claim pull request #22
Opened 2024-04-17 16:11 UTC by Phanco

### What was the problem?

This PR resolves #21

### How was it solved?
New command `generate-airdrop-merkle-tree` added.

### How was it tested?
Test cases updated surrounding `generate-airdrop-merkle-tree` command

2024-04-18 10:42 UTC, sergeyshemyakov requested changes

2024-04-18 10:42 UTC, sergeyshemyakov commented on packages/tree-builder/src/applications/generate-airdrop-merkle-tree/index.ts
> +			balanceBeddows: ((newBalanceBeddows * percent) / BigInt(100)).toString(),
I see that you write balances in beddows into the Merkle tree. This creates a contradiction with [airdrop claiming](https://github.com/LiskHQ/lisk-contracts/blob/feature/migration-airdrop/src/L2/L2Airdrop.sol#L283), where the balances are assumed to be in wei.

I am not sure whether it would be better to write beddows into the Merkle tree and convert into wei in the smart contract, or write already the wei amount into the tree. How have you done it in staking contracts?

2024-04-18 10:42 UTC, sergeyshemyakov commented on packages/tree-builder/src/commands/generate-airdrop-merkle-tree/index.ts
> +			cutoff: cutOff,
Should it not be `'cutoff': cutoff,`?

2024-04-18 10:42 UTC, sergeyshemyakov commented on packages/tree-builder/src/commands/generate-airdrop-merkle-tree/index.ts
> +export default class GenerateAirdropMerkleTree extends Command {
Maybe I have missed something, but does this code generate an actual Merkle tree? Or will the Merkle tree generation be handled later by a different already existing piece of code?

2024-04-18 11:52 UTC, Phanco commented on packages/tree-builder/src/commands/generate-airdrop-merkle-tree/index.ts
> +			cutoff: cutOff,
there is no hyphen in `cutoff`, that's why quote is not necessary here

2024-04-18 12:15 UTC, Phanco commented on packages/tree-builder/src/applications/generate-airdrop-merkle-tree/index.ts
> +			balanceBeddows: ((newBalanceBeddows * percent) / BigInt(100)).toString(),
You're right, in the airdrop contract there's not multiplication from beddows to wei, I think I should use the exact amount the user is going to get on L2.

2024-04-18 14:42 UTC, matjazv approved these changes
PR is approved.

I have just a question how Merkle trees and their roots will be generated?
Is there any script which needs to be executed and trees will be generated, or would we need to manually execute generation of Merkle tree for Claim process and for Airdrop process with some command?

2024-04-18 14:53 UTC, Phanco commented
> PR is approved.
> 
> I have just a question how Merkle trees and their roots will be generated? Is there any script which needs to be executed and trees will be generated, or would we need to manually execute generation of Merkle tree for Claim process and for Airdrop process with some command?

Just like the original merkle tree generation, this command also generates tree by call `await buildTreeJson(outputPath, airdropAccounts);`, since the balance is the only difference, we can reuse that function

2024-04-18 14:53 UTC, Phanco commented on packages/tree-builder/src/commands/generate-airdrop-merkle-tree/index.ts
> +export default class GenerateAirdropMerkleTree extends Command {
A tree will also be generated in json file like before

2024-04-19 13:56 UTC, Phanco commented
Since the Merkle Encoding is changed (multisig removed, uint64 -> uint256). So I copied the build tree script and make changes from it, such that the old script is remain untouched

2024-04-19 14:06 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-airdrop-merkle-tree/index.ts
> +				: [];
maybe good to have function like
```
export function readExcludedAddresses(excludedAddressesPath: string | undefined): string[] {
	if (excludedAddressesPath === undefined) {
		return [];
	}
	const resolvedPath = path.resolve(excludedAddressesPath.replace('~', os.homedir()));
	if (!fs.existsSync(resolvedPath)) {
		throw new Error(`${resolvedPath} does not exist`);
	}

	const addresses = fs.readFileSync(resolvedPath, 'utf-8').split('\n');

	for (const address of addresses) {
		cryptoAddress.validateLisk32Address(address);
	}
	return addresses;
}
```
in the util to be tested separately

2024-04-20 17:06 UTC, Phanco commented on packages/tree-builder/src/commands/generate-airdrop-merkle-tree/index.ts
> +				: [];
Done

2024-04-20 17:08 UTC, Phanco commented
FYI: The original plan is to reuse `checkEligibility` endpoint, but since we're adding a new [endpoint](https://github.com/LiskHQ/lisk-token-claim/issues/26) for airdrop, `balanceBeddows` in airdrop can be renamed to `balanceWei`

2024-04-20 23:24 UTC, sergeyshemyakov reviewed
I want to have another fresh look tomorrow.

2024-04-20 23:24 UTC, sergeyshemyakov commented on packages/tree-builder/src/applications/generate-airdrop-merkle-tree/build_airdrop_tree.ts
> +	tree: StandardMerkleTree<(string | number | Buffer | string[])[]>;
Shouldn't the line here be:
`tree: StandardMerkleTree<(string | number)[]>;`?

2024-04-21 06:50 UTC, shuse2 approved these changes

2024-04-21 07:33 UTC, matjazv approved these changes

2024-04-21 11:54 UTC, Phanco commented on packages/tree-builder/src/applications/generate-airdrop-merkle-tree/build_airdrop_tree.ts
> +	tree: StandardMerkleTree<(string | number | Buffer | string[])[]>;
The `StandardMerkleTree` from library can accept all types above, so even though we're not using all of them I'm including those types anyway 👍

2024-04-21 12:11 UTC, sergeyshemyakov approved these changes

2024-04-21 12:29 UTC, merged