Add Taking Snapshot document
LiskHQ/lisk-token-claim pull request #31
Opened 2024-04-29 15:45 UTC by Phanco

### What was the problem?

This PR resolves #30

### How was it solved?
Created document `Taking_Snapshot.md`
Updated other READMEs to include Airdrop Merkle Tree

2024-04-30 10:21 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +   $ git clone git@github.com:LiskHQ/lisk-token-claim.git && cd lisk-token-claim
Question: should this be `lisk-token-claim` or `lisk-token-claim-private`? 🤔

2024-04-30 10:22 UTC, matjazv commented on documentation/Taking_Snapshot.md
> +   $ git clone git@github.com:LiskHQ/lisk-token-claim.git && cd lisk-token-claim
I think `lisk-token-claim-private` will never be exposed to the public.

2024-05-01 06:58 UTC, matjazv requested changes

2024-05-01 06:58 UTC, matjazv commented on README.md
> +    - L2 Token Airdrop
It is called `Migration Airdrop` so maybe change this line to:

```suggestion
    - Migration Airdrop
```

2024-05-01 06:58 UTC, matjazv commented on README.md
> +  - Obtaining Lisk v4 Snapshot
New line is missing like it's in line 57.

2024-05-01 06:58 UTC, matjazv commented on documentation/Taking_Snapshot.md
> +2. **L2 Token Airdrop** - A Merkle Tree that rewards LSK holders for migrating from Lisk v4 to Lisk L2
`Migration Airdrop`

2024-05-01 06:58 UTC, matjazv commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/exclude_addresses.txt
For latest snapshot 30.4.2024 it says:
`85835 Accounts to generate`
I would say this is correct number.

I provided list of excluded addresses, but I don't see any output if this was taken into account or not.
Perhaps it should display all excluded addresses?

2024-05-01 06:58 UTC, matjazv commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/excluded_airdrop_addresses.txt
For latest snapshot 30.4.2024 it says:
`12232 Accounts to generate`
I would say this is correct number.

When executing this command excluded addresses are shown like:
`1 addresses to be excluded from airdrop:`
Something similar could be provided also for `generate-merkle-tree` command.

2024-05-02 09:44 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/exclude_addresses.txt
Good suggestion 👍 , while this PR is tackling documentation, I have opened this [issue](https://github.com/LiskHQ/lisk-token-claim-private/issues/32)

2024-05-02 09:48 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/excluded_airdrop_addresses.txt
The issue also includes this one

2024-05-02 09:55 UTC, Phanco commented on README.md
> +    - L2 Token Airdrop
Updated 👍

2024-05-02 09:55 UTC, Phanco commented on README.md
> +  - Obtaining Lisk v4 Snapshot
Updated 👍

2024-05-02 09:55 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +2. **L2 Token Airdrop** - A Merkle Tree that rewards LSK holders for migrating from Lisk v4 to Lisk L2
Updated 👍

2024-05-02 09:59 UTC, matjazv approved these changes

2024-05-06 09:11 UTC, AndreasKendziorra requested changes

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +Which the Merkle Tree is used for Token Migration and future Airdrops.
```suggestion
The Merkle Trees are used for the Token Migration and future Airdrops.
```

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +This document focuses on converting Lisk Snapshot to Merkle Tree using `tree-builder`.
```suggestion
This document focuses on converting a Lisk Snapshot to Merkle Tree using `tree-builder`.
```

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +There are 2 planned Merkle Tree from Lisk:
```suggestion
There are 2 planned Merkle Trees for Lisk:
```

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +1. **Lisk Token Migration** - The main Merkle Tree to let allow users migrate their LSK Token from Lisk Mainchain (Lisk Chain) to LSK L2 Network (L2 Chain).
```suggestion
1. **Lisk Token Migration** - The main Merkle Tree to let users migrate their LSK Token from Lisk L1 to LSK L2 Network (L2 Chain).
```

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +2. **Migration Airdrop** - A Merkle Tree that rewards LSK holders for migrating from Lisk v4 to Lisk L2
```suggestion
2. **Migration Airdrop** - A Merkle Tree that rewards LSK holders for migrating from Lisk L1 to Lisk L2
```

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +1. Download and extract blockchain data of block [24,823,618](https://snapshots.lisk.com/mainnet/blockchain-24823618.db.tar.gz) from Lisk Snapshots. Blockchain data will be available soon after the b
Should we rather link to the folder instead of the file such that one does not get 404 before the file is there?

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +   $ curl https://snapshots.lisk.com/mainnet/blockchain-24823618.db.tar.gz -o /path/to/blockchain.db.tar.gz
a hint that the folder `/path/to` must already exist would be good. Alternatively, one could just remove `/path/to` such that the current folder is used. Then users could also just copy and past the command without manual steps which would be nice.

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +   $ git clone git@github.com:LiskHQ/lisk-token-claim.git && cd lisk-token-claim
could we please write every command without the preceding `$` such that users can just copy and paste the command?

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +4. (Optional) Prepare `exclude_addresses.txt` and `exclude_airdrop_addresses.txt` \
I assume this is also the step that removes the addresses of some exchanges for the migration. Then this list should be available for everyone such that every user will compute the same Merkle tree. Therefore, we must name or link to the correct file here, or list all addresses here.

If we use different lists for the two different use cases, then this step should maybe be moved to the "Lisk Token Migration" and "Migration Airdrop" section.

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +| db-path                 | Database path, where your state.db is located        | True     |                    |
A hint that state.db was created at step 1 of the preparation would be good. Then it's easier to find the path. Following the commands from above, this should be `../../../`, right?

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +$ mkdir -p /path/to/migration
wouldn't it be easier to specify here a relative path such that the user does not need to do anything manual? It could be `../../../Merkle-tree-data` to have the folder `Merkle-tree-data` in the folder where the preparation started.
Then this path should also be used below in the command.

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +--db-path=/path/to \
I would use the path that should be the right one when following the steps from above (`../../..`?) to avoid that users have to do anything manually.

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/exclude_addresses.txt
1. so this file will exist in the repository in the future? Or is it the one created in step 4 of the preparation? If the latter is the case, the path does not match.
2. I receive the error `Error: Nonexistent flag: --excluded-addresses-path=../../data/mainnet/exclude_addresses.txt`. Also when choosing a different path including `""`.

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +$ mkdir -p /path/to/airdrop
same as above: rather using a specific relative path

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +--db-path=/path/to \
same as above: I would use `../../../`

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/exclude_addresses.txt
about 2: is it because it was only implemented in `lisk-token-claim-private`? If yes, what's the current plan when this feature will be integrated into the public repository?

2024-05-06 09:11 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +$ ./bin/run.js generate-airdrop-merkle-tree \
I guess this works right now only with the private repository, but not with the public one, right?

2024-05-06 09:11 UTC, AndreasKendziorra commented on packages/tree-builder/README.md
> +P.S. If the address is not a multisig address, `NUMBER_OF_SIGNATURES` would be `0,` `MANDATORY_KEYS` and `OPTIONAL_KEYS` be `[]`
```suggestion
If the address is not a multisig address, `NUMBER_OF_SIGNATURES` would be `0,` `MANDATORY_KEYS` and `OPTIONAL_KEYS` be `[]`
```

2024-05-06 09:11 UTC, AndreasKendziorra commented on packages/tree-builder/README.md
> +P.S. If the address is not a multisig address, `NUMBER_OF_SIGNATURES` would be `0,` `MANDATORY_KEYS` and `OPTIONAL_KEYS` be `[]`
I think it's very uncommon outside of letters/mails :)

2024-05-06 09:51 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +$ ./bin/run.js generate-airdrop-merkle-tree \
correct

2024-05-08 08:19 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +Which the Merkle Tree is used for Token Migration and future Airdrops.
updated

2024-05-08 08:19 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +This document focuses on converting Lisk Snapshot to Merkle Tree using `tree-builder`.
updated

2024-05-08 08:19 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +There are 2 planned Merkle Tree from Lisk:
updated

2024-05-08 08:19 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +1. **Lisk Token Migration** - The main Merkle Tree to let allow users migrate their LSK Token from Lisk Mainchain (Lisk Chain) to LSK L2 Network (L2 Chain).
updated

2024-05-08 08:19 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +2. **Migration Airdrop** - A Merkle Tree that rewards LSK holders for migrating from Lisk v4 to Lisk L2
updated

2024-05-08 08:21 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/exclude_addresses.txt
Yes, the version in public repo is older and does not include exclude address feature yet. I believe at the public side it will be updated before migration date.

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +1. Download and extract blockchain data of block [24,823,618](https://snapshots.lisk.com/mainnet/blockchain-24823618.db.tar.gz) from Lisk Snapshots. Blockchain data will be available soon after the b
Updated this part, now it has link to the snapshot directory, and an alternative command to get latest, non-heigh specific snapshot

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +   $ curl https://snapshots.lisk.com/mainnet/blockchain-24823618.db.tar.gz -o /path/to/blockchain.db.tar.gz
updated to use relative path

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +   $ git clone git@github.com:LiskHQ/lisk-token-claim.git && cd lisk-token-claim
removed :D

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +4. (Optional) Prepare `exclude_addresses.txt` and `exclude_airdrop_addresses.txt` \
Relocated this part with more explanation

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +| db-path                 | Database path, where your state.db is located        | True     |                    |
Updated, now should be clearer

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +$ mkdir -p /path/to/migration
updated to use relative path

2024-05-08 08:22 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +--db-path=/path/to \
updated to use relative path

2024-05-08 08:23 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +$ mkdir -p /path/to/airdrop
updated to use relative path

2024-05-08 08:23 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +--db-path=/path/to \
updated to use relative path

2024-05-08 08:23 UTC, Phanco commented on packages/tree-builder/README.md
> +P.S. If the address is not a multisig address, `NUMBER_OF_SIGNATURES` would be `0,` `MANDATORY_KEYS` and `OPTIONAL_KEYS` be `[]`
Done

2024-05-08 09:48 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +There are 2 planned Merkle Tree from Lisk:
"Trees" should be plural

2024-05-08 10:10 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +# Addresses inside the text file will be excluded from ?igration, separated by line-break.
```suggestion
# Addresses inside the text file will be excluded from Migration, separated by line-break.
```

2024-05-08 10:10 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +4. (Optional) Prepare `exclude_addresses.txt` and `exclude_airdrop_addresses.txt` \
I would go even further and remove the optional steps of creating the .txt files in lines 64 and 94. Because you are documenting very concrete scenarios in which specific files must be used. It's not about the general process of generating a Merkle tree from a snapshot.

2024-05-08 10:27 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +--excluded-addresses-path=../../data/mainnet/exclude_addresses.txt
I asked on slack when this will happen.

2024-05-08 10:37 UTC, AndreasKendziorra requested changes

2024-05-08 10:37 UTC, AndreasKendziorra commented on documentation/Taking_Snapshot.md
> +   curl https://snapshots.lisk.com/mainnet/blockchain.db.tar.gz -o ./blockchain.db.tar.gz
Now I just realized that this line will overwrite `blockchain.db.tar.gz` from line 26 if one does copy and paste with the whole code block. I would therefore remove this one here, or at least comment it out.

2024-05-08 11:18 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +# Addresses inside the text file will be excluded from ?igration, separated by line-break.
oops, updated

2024-05-08 11:18 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +There are 2 planned Merkle Tree from Lisk:
updated

2024-05-08 11:18 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +   curl https://snapshots.lisk.com/mainnet/blockchain.db.tar.gz -o ./blockchain.db.tar.gz
added `#`

2024-05-08 11:23 UTC, Phanco commented
> I would go even further and remove the optional steps of creating the .txt files in lines 64 and 94. Because you are documenting very concrete scenarios in which specific files must be used. It's not about the general process of generating a Merkle tree from a snapshot.

You're right, actually there is no point for users to make changes to those files. I have included the path of the file we're going to use in the description, and removed the whole (optional) part

2024-05-08 11:35 UTC, AndreasKendziorra approved these changes

2024-05-08 12:20 UTC, merged