Update Taking Snapshot document
LiskHQ/lisk-token-claim pull request #46
Opened 2024-05-14 13:57 UTC by Phanco

### What was the problem?

This PR resolves #30

### How was it solved?
Updated Taking Snapshot document with more decentralised option.

2024-05-14 14:13 UTC, Phanco commented on documentation/Taking_Snapshot.md
> +After Merkle Tree generation, the Merkle Root can be verified at `./migration`
Is there a placeholder I can put here, that users can verify the merkle tree they have generated?

2024-05-14 14:48 UTC, sameersubudhi requested changes
Please check the following recommendations.

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
>  This document focuses on converting a Lisk Snapshot to Merkle Tree using `tree-builder`.
```suggestion
This document focuses on generating the Merkle Tree from a Lisk Core snapshot using `tree-builder`.
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +The Merkle Tree is used for the Token Migration, which let users migrate their LSK Token from Lisk L1 to LSK L2 Network (L2 Chain).
```suggestion
The Merkle Tree is used for the Token Migration, which lets the user migrate their LSK Token from the Lisk L1 to the LSK L2 Network (L2 Chain).
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
>  - Node v18
```suggestion
- NodeJS v18
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +1. Synchronize blockchain using `lisk-core`. It will shut down itself after Snapshot Height (#24,823,618) has been reached.
```suggestion
1. Synchronize blockchain using `lisk-core`. The node will automatically shut down itself after about a round after the Snapshot Height (#24,823,618) has been finalized, i.e. block #24,823,721 is finalized. Under ideal conditions, this might take about ~40-45 mins after the block at Snapshot Height is generated.
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +2. Go back to home folder, or start a new terminal if the `lisk-core` is still running, clone and install `lisk-token-claim`.
```suggestion
2. Go back to home folder, or start a new terminal if the `lisk-core` instance is still running, clone and install `lisk-token-claim`.
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +   After synchronization, the snapshot data of the specific height can be found in `./snapshot/backup/`
```suggestion
   After synchronization, the snapshot data for the specified height (`system.backup.height`) in the Lisk Core node config can be found in `./snapshot/backup/`
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +   git clone git@github.com:LiskHQ/lisk-token-claim.git
It's better to suggest the https URL instead since SSH URL will require the user to have access to the repo as a team member.
```suggestion
   git clone https://github.com/LiskHQ/lisk-token-claim.git
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +   At this stage your directory should look like this:
```suggestion
   At this stage, your directory structure should look like this:
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +   home/
```suggestion
   $LISK_HOME/
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +   yarn && yarn build
```suggestion
   yarn install --frozen-lockfile && yarn build
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +After Merkle Tree generation, the Merkle Root can be verified at `./migration`
```suggestion
After Merkle Tree generation, the Merkle Root can be verified from `./migration/merkle-root.json`
```

2024-05-14 14:48 UTC, sameersubudhi commented on documentation/Taking_Snapshot.md
> +   yarn && yarn build
```suggestion
   yarn install --frozen-lockfile && yarn build
```

2024-05-14 15:27 UTC, sameersubudhi approved these changes
LGTM 👍

2024-05-15 09:20 UTC, nagdahimanshu approved these changes
Left one optional suggestion but overall LGTM 👍

2024-05-15 09:20 UTC, nagdahimanshu commented on documentation/Taking_Snapshot.md
> +2. Go back to home folder, or start a new terminal if the `lisk-core` instance is still running, clone and install `lisk-token-claim`.
Not important (optional)
```suggestion
2. Go back to home directory, or start a new terminal if the `lisk-core` instance is still running, clone and install `lisk-token-claim`.
```

2024-05-15 09:39 UTC, merged