Improve claim-backend logging
LiskHQ/lisk-token-claim pull request #64
Opened 2024-05-29 13:54 UTC by Phanco

### What was the problem?

This PR resolves #62

### How was it solved?

### How was it tested?

2024-05-29 15:50 UTC, shuse2 requested changes

2024-05-29 15:50 UTC, shuse2 commented on packages/claim-backend/README.md
> +| BACKEND_LOGGER_LEVEL | Logger level in backend (trace/debug/info/warn/error/fatal) (Default: debug)                                                                         | false
let's set the default to be `info` so on production, we can use without changing

2024-05-29 15:50 UTC, shuse2 commented on packages/claim-backend/README.md
> +  - `DEBUG`: When sending success RPC response to client.
I think this can be `info` level

2024-06-06 23:09 UTC, has5aan approved these changes
LGTM, one inquiry, tried the logger.ts file in a simple setup, and discovered that the error stack is being returned as response, perhaps not an issue for our use-case as the repository is already public or how the endpoint is consumed?

2024-06-07 12:21 UTC, Phanco commented
> LGTM, one inquiry, tried the logger.ts file in a simple setup, and discovered that the error stack is being returned as response, perhaps not an issue for our use-case as the repository is already public or how the endpoint is consumed?

Error stack will be hidden when `NODE_ENV=production` and this flag has been used in prod

2024-06-07 14:56 UTC, shuse2 approved these changes

2024-06-07 15:02 UTC, merged