Token Claim Backend
LiskHQ/lisk-token-claim pull request #8
Opened 2024-01-10 18:53 UTC by Phanco

### What was the problem?

This PR resolves #5

### How was it solved?

- ExpressJS used as the backbone of the server, with the aid of PostgreSQL DB
- Endpoints added using JSON RPC 2.0 standard

### How was it tested?
Test cases added for endpoints and util functions

2024-02-07 13:05 UTC, shuse2 requested changes

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/.env.example
> +DB_PASSWORD=let-me-in
i think just `passwd` is good enough default

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/.env.example
> +MERKLE_TREE_PATH=/Users/lisk-token-claim/data/merkle-tree-result-detailed.json
relative path doesn't work?

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/src/models/Signature.model.ts
> +import {
filename should be `signature.model.ts`?

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/src/controllers/check-eligibility.ts
> +		return Promise.reject(new Error(ErrorCode.INVALID_LSK_ADDRESS));
```suggestion
		throw new Error(ErrorCode.INVALID_LSK_ADDRESS);
```

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/src/controllers/submit-multisig.ts
> +		return Promise.reject(new Error(ErrorCode.INVALID_LSK_ADDRESS));
in the async function, no need to use `Promise.reject`. you can just `throw`

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/src/utils/error.ts
> +enum ErrorCode {
```suggestion
export enum ErrorCode {
```

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/src/utils/error.ts
> +export { ErrorCode };
no need with above

2024-02-07 13:05 UTC, shuse2 commented on packages/claim-backend/src/utils/error.ts
> +enum ErrorCode {
same for other places

2024-02-07 13:10 UTC, Phanco commented on packages/claim-backend/.env.example
> +MERKLE_TREE_PATH=/Users/lisk-token-claim/data/merkle-tree-result-detailed.json
Possible, updating to `MERKLE_TREE_PATH=../../data/merkle-tree-result-detailed.json`

2024-02-07 13:19 UTC, Phanco commented on packages/claim-backend/src/utils/error.ts
> +export { ErrorCode };
updated

2024-02-07 13:19 UTC, Phanco commented on packages/claim-backend/src/controllers/submit-multisig.ts
> +		return Promise.reject(new Error(ErrorCode.INVALID_LSK_ADDRESS));
updated

2024-02-07 13:19 UTC, Phanco commented on packages/claim-backend/src/controllers/check-eligibility.ts
> +		return Promise.reject(new Error(ErrorCode.INVALID_LSK_ADDRESS));
updated

2024-02-07 13:19 UTC, Phanco commented on packages/claim-backend/.env.example
> +DB_PASSWORD=let-me-in
updated

2024-02-07 13:19 UTC, Phanco commented on packages/claim-backend/src/models/Signature.model.ts
> +import {
updated

2024-02-07 13:26 UTC, Phanco commented on packages/claim-backend/src/utils/error.ts
> +enum ErrorCode {
Changed `export {}` to exporting function/params directly in other files as well

2024-02-07 15:09 UTC, shuse2 commented on packages/claim-backend/src/controllers/submit-multisig.ts
> +		return Promise.reject(new Error(ErrorCode.INVALID_LSK_ADDRESS));
same for the `resolve`. you can just return value

2024-02-07 15:58 UTC, shuse2 requested changes

2024-02-07 15:58 UTC, shuse2 commented on packages/claim-backend/src/index.ts
> +const server = new JSONRPCServer();
this should be defined in the function below?

2024-02-07 15:58 UTC, shuse2 commented on packages/claim-backend/src/index.ts
> +void (async () => {
`void` i think is not needed?

2024-02-07 15:58 UTC, shuse2 commented on packages/claim-backend/src/index.ts
> +	{
unnecessary bracket here?

2024-02-07 15:58 UTC, shuse2 commented on packages/claim-backend/src/utils/read-json.ts
> +};
if it's one line does it make sense to wrap it...?

2024-02-07 15:58 UTC, shuse2 commented on packages/claim-backend/test/controllers/submit-multisig.test.ts
> +		}
in general, try-catch should be avoided because if the function doesn't throw, it will be false positive

2024-02-07 16:52 UTC, Phanco commented on packages/claim-backend/src/index.ts
> +void (async () => {
I will get complain from eslint without `void`

> ESLint: Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator.(@typescript-eslint/no-floating-promises)

2024-02-07 16:54 UTC, Phanco commented on packages/claim-backend/src/utils/read-json.ts
> +};
With these 2 wrappers I could mock `fs` related tests easily

2024-02-07 17:44 UTC, Phanco commented on packages/claim-backend/test/controllers/submit-multisig.test.ts
> +		}
Updated, now using chai-as-promise

2024-02-07 17:44 UTC, Phanco commented on packages/claim-backend/src/index.ts
> +	{
updated

2024-02-07 17:54 UTC, Phanco commented on packages/claim-backend/src/controllers/submit-multisig.ts
> +		return Promise.reject(new Error(ErrorCode.INVALID_LSK_ADDRESS));
Updated

2024-02-07 20:17 UTC, shuse2 commented on packages/claim-backend/src/index.ts
> +	app.use(express.urlencoded({ extended: true }));
don't we need to have `cors` setting?

2024-02-08 16:13 UTC, Phanco commented on packages/claim-backend/src/index.ts
> +	app.use(express.urlencoded({ extended: true }));
Added cors, thank you for the remind

2024-02-12 08:01 UTC, shuse2 approved these changes

2024-02-12 12:40 UTC, has5aan approved these changes
🚀 
Just an inquiry, would introducing .nvmrc for the package make sense as we consume, `lisk-elements`?

2024-02-12 14:32 UTC, merged