Snapshot Taker
LiskHQ/lisk-token-claim pull request #9
Opened 2024-01-18 16:29 UTC by Phanco

### What was the problem?

This PR resolves #2

### How was it solved?
`state.db` is read instead of reading JSON file
an array of accounts will be generated, and the rest of the process are performed the same as the previous PR

### How was it tested?
Unit Tests updated for

1. snapshot taking
2. cli

2024-01-31 10:11 UTC, shuse2 requested changes

2024-01-31 10:11 UTC, shuse2 commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +		Number(account.balanceBeddows),
type of balance is uint64, so it can go over the safe integer range

2024-01-31 10:11 UTC, shuse2 commented on packages/tree-builder/.gitignore
> +test/data/*.db
maybe we can keep this in the root level .gitignore?

2024-01-31 10:11 UTC, shuse2 commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +		const balanceBeddows = Math.round(balance * LSK_MULTIPLIER).toString();
probably good to properly use bigint

2024-01-31 10:11 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		dbPath: Flags.string({
i think it's better to have flag as format like `--db-path`. same for other flags

2024-01-31 10:11 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +			default: path.join(__dirname, '../../../../../data'),
Once the command is installed, i think this path doesn't make so much sense. maybe default path can be `cwd`?

2024-01-31 10:11 UTC, shuse2 commented on packages/tree-builder/src/utils.ts
> +		balance.lockedBalances.reduce((acc, cur) => acc + cur.amount, BigInt(0))
Something to confirm with @AndreasKendziorra, what we should do with locked amount for reward sharing

2024-01-31 14:56 UTC, AndreasKendziorra requested changes

2024-01-31 14:56 UTC, AndreasKendziorra commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		const rdb = new StateDB(stateDbPath, { readonly: true });
So the DB in the file `state.db` contains only the state for a certain height? Which means, once we know the snapshot height, `state.db` must be created for this height, right? And how is `state.db` actually created?

2024-01-31 14:56 UTC, AndreasKendziorra commented on packages/tree-builder/src/constants.ts
> +// moduleName = "token", index = 0
It took me a bit to see why we need to add `Buffer.alloc(2, 0)`. Maybe you could add here in the comment "substore prefix = 0x00" instead of "index = 0". Same for line 18

2024-01-31 14:56 UTC, AndreasKendziorra commented on packages/tree-builder/src/utils.ts
> +		balance.lockedBalances.reduce((acc, cur) => acc + cur.amount, BigInt(0))
You mean locked amount for staking? We agreed to incorporate all locked amounts to prevent that stakers have to unlock on our L1 in order to claim on L2.
So, the proposed implementation is correct.

2024-01-31 14:56 UTC, AndreasKendziorra commented on packages/tree-builder/test/applications/create_snapshot.test.ts
> +				Buffer.concat([TOKEN_PREFIX, account.address, tokenId]),
I'm not sure if keys in the DB are equal to the ones in the state tree. If yes, then the key should be
`storePrefix + substorePrefix + sha256(storeKey) = TOKEN_PREFIX +  sha256(storeKey)  
= TOKEN_PREFIX + sha256(account.address + tokenId)`

The same for the other keys below.

2024-01-31 14:56 UTC, AndreasKendziorra commented on packages/tree-builder/test/commands/generate-merkle-tree/index.test.ts
> +				Buffer.concat([TOKEN_PREFIX, utils.getRandomBytes(20), tokenId]),
Same as above: the keys do not match with the ones in the state tree.

2024-01-31 14:56 UTC, AndreasKendziorra commented on packages/tree-builder/test/commands/generate-merkle-tree/index.test.ts
> +				Buffer.concat([TOKEN_PREFIX, utils.getRandomBytes(20), tokenId]),
same as above

2024-01-31 15:14 UTC, Phanco commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		const rdb = new StateDB(stateDbPath, { readonly: true });
Correct. We need to have a mechanism that the client to stop syncing at a certain height

2024-01-31 15:35 UTC, Phanco commented on packages/tree-builder/test/applications/create_snapshot.test.ts
> +				Buffer.concat([TOKEN_PREFIX, account.address, tokenId]),
From the implementation that I saw on lisk-sdk, seems that the storeKey would not be hashed 🤔 
https://github.com/LiskHQ/lisk-sdk/blob/20625936c96d694fff83cda42dc4086ed22423f8/framework/src/modules/token/stores/user.ts#L89

After the `getKey` function above, no sha256 step are made

2024-02-02 11:27 UTC, Phanco commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +		Number(account.balanceBeddows),
Update to use Buffer instead 👍

2024-02-02 11:28 UTC, Phanco commented on packages/tree-builder/.gitignore
> +test/data/*.db
removed

2024-02-02 11:29 UTC, Phanco commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +		const balanceBeddows = Math.round(balance * LSK_MULTIPLIER).toString();
As the merkleTree lib by oz does not support bigint nor string, string is used in json file as it is the default output of the snapshot, and has higher readability

2024-02-02 14:04 UTC, Phanco commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		dbPath: Flags.string({
updated, also for `output-path`

2024-02-05 10:51 UTC, Phanco commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		const rdb = new StateDB(stateDbPath, { readonly: true });
As discussed on channel, the snapshot file with specific height will be ready.

2024-02-05 13:05 UTC, AndreasKendziorra commented on packages/tree-builder/test/applications/create_snapshot.test.ts
> +				Buffer.concat([TOKEN_PREFIX, account.address, tokenId]),
ok. @shuse2 could you please confirm that the DB uses the key format 
`storePrefix + substorePrefix + storeKey`
instead of 
`storePrefix + substorePrefix + sha256(storeKey)`
as the state tree does?

2024-02-05 13:59 UTC, AndreasKendziorra requested changes
I left some older comments open until I get the confirmation from Shu.

2024-02-05 13:59 UTC, AndreasKendziorra commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +		utils.intToBuffer(account.balanceBeddows, 8),
In line 40-44, this value will be interpreted as a uint64. Are we sure that the conversion from buffer to uint64 works as intended?

2024-02-05 13:59 UTC, AndreasKendziorra commented on packages/tree-builder/test/applications/build_tree.test.ts
> +			const encodedMessage = defaultAbiCoder.encode(LEAF_ENCODING, createPayload(accounts[i]));
Related to my other comment from above: It's not obvious to me that the integer `accounts[i].balanceBeddows` will be correctly encoded in encodedMessage. 

It could be tested by 
- constructing a Merkle tree based on one account, but in two different ways and checking that both ways provide the same root
- first way computes the tree via `buildTree` based on the single account
- second way takes the same account as in the first way, but the `balanceBeddows` property is of type number. Then, Merkle tree is constructed manually using `StandardMerkleTree.of(...)`

2024-02-05 15:58 UTC, Phanco commented on packages/tree-builder/test/applications/build_tree.test.ts
> +			const encodedMessage = defaultAbiCoder.encode(LEAF_ENCODING, createPayload(accounts[i]));
I made an update such that it accepts string number, so `balanceBeddows` can be passed to the library without Buffer conversion. However, I added one test according to your suggestion to test the integrity of `buildTree`

2024-02-05 15:58 UTC, Phanco commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +		utils.intToBuffer(account.balanceBeddows, 8),
updated

2024-02-06 09:09 UTC, shuse2 commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +		const balanceBeddows = Math.round(balance * LSK_MULTIPLIER).toString();
what I meant here is balance * LSK_MULTIPLIER goes out of the safe integer range. so when you compute, you should use bigint before converting to string

2024-02-06 09:10 UTC, shuse2 commented on packages/tree-builder/test/applications/create_snapshot.test.ts
> +				Buffer.concat([TOKEN_PREFIX, account.address, tokenId]),
`storePrefix + substorePrefix + storeKey` is correct for DB fetch

2024-02-06 10:45 UTC, shuse2 commented on packages/tree-builder/src/applications/generate-merkle-tree/build_tree.ts
> +		utils.intToBuffer(account.balanceBeddows, 8),
so we are now passing the string directly to the library?

2024-02-06 13:43 UTC, Phanco commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +		const balanceBeddows = Math.round(balance * LSK_MULTIPLIER).toString();
Now using `BigNumber.js` 👍 Even `BigInt` supports up to `2**53 - 1` only

2024-02-06 14:41 UTC, shuse2 commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +		const balanceBeddows = Math.round(balance * LSK_MULTIPLIER).toString();
🤔 
I think BigInt supports arbitrary big numbers, and with bigint support, i don't see reason now to use BigNumber.js

2024-02-06 15:26 UTC, Phanco commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +		const balanceBeddows = Math.round(balance * LSK_MULTIPLIER).toString();
ah I misunderstood the `bigInt` and thought it has a limit of 2**53 -1 (it was the limit of `Number`). Now I used another method for generating random bigint

2024-02-06 15:28 UTC, Phanco commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +const RANDOM_BYTES_RANGE = 5;
Used a smaller random balance here such that when testing claim contract using the data generated from this CLI, we don't need to prepare absurd amount of balance in Claim contract.

2 ** 40 / 10 ** 8 ~= 11000 LSK

A full 0 - 2**64 -1 range of random balances is still used in test cases

2024-02-07 08:43 UTC, shuse2 commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		tokenId: Flags.string({
```suggestion
		'token-id': Flags.string({
```

2024-02-07 08:44 UTC, shuse2 reviewed
Minor flag inconsistency, but otherwise LGTM!

2024-02-07 09:50 UTC, Phanco commented on packages/tree-builder/src/commands/generate-merkle-tree/index.ts
> +		tokenId: Flags.string({
Updated 👍

2024-02-07 12:20 UTC, shuse2 approved these changes

2024-02-07 14:04 UTC, AndreasKendziorra requested changes
Just one tiny thing left. Otherwise looks good to me

2024-02-07 14:04 UTC, AndreasKendziorra commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +// Random Balance in Beddows between 0 - 2 ** 8 * (RANDOM_BYTES_RANGE)
```suggestion
// Random Balance in Beddows between 0 - 2 ** (8 * RANDOM_BYTES_RANGE)
```

2024-02-07 18:05 UTC, Phanco commented on packages/tree-builder/src/applications/example/create_accounts.ts
> +// Random Balance in Beddows between 0 - 2 ** 8 * (RANDOM_BYTES_RANGE)
done 🖖

2024-02-08 07:59 UTC, AndreasKendziorra approved these changes

2024-02-08 11:26 UTC, merged